Add support for timestamp in the link
ag91/ol-emacs-slack pull request #2
Opened 2020-11-06 09:48 UTC by Konubinix

So that you can go back not only to the room, but also to the
message that triggered the capture of the link.

I am not conviced with the part where the link is split then reconstructed (without the ts) to be given to `ol/slack-string-to-room`. It does not look very elegant to me. Nevertheless, IMHO, an elegant way of playing with the link would be to parse the link value only once and use this parsed object in the function rather than parsing in several places (with s-split).

2020-11-07 22:03 UTC, ag91 commented
Hey thanks for the nice words and for your work on the PR.

I tried it out and I see that it adds the timestamp in HH:MM format, but
when I try to follow the link I do not get to the right message.

What I tried was to store a link of a message, move the cursor at the
top of the buffer and try to follow the link: I just stay at the top.
Am I doing something wrong?

Also I agree with you: we can just make the following transformation

[emacs-slack:TEAM - #CHANNEL - TIME.STAMP] -> (:team TEAM :channel CHANNEL :timestamp TIME.STAMP)

so that we pass a structure ("the parsed object") that represent the link information around.

By  the way have you checked this function in emacs-slack slack-buffer.el:

```
(defun slack-buffer-goto (ts)
  (let ((point (slack-buffer-ts-eq (point-min) (point-max) ts)))
    (when point
      (goto-char point))))
```
I sort of think you need that to move to the right place. Although I guess it would not work if your message is not among the messages loaded so far.

2020-11-10 13:15 UTC, Konubinix commented
ag91 <notifications@github.com> writes:

[...]

> I tried it out and I see that it adds the timestamp in HH:MM format

Actually, the HH:MM format is only the description part. I found out
that the lui.el library already put the text-property
'lui-formatted-time-stamp so I just took it.

The stamp is got from the property 'ts, put by slack.el. It is in the
slack timestamp format.

> , but when I try to follow the link I do not get to the right message.
>
> What I tried was to store a link of a message, move the cursor at the
> top of the buffer and try to follow the link: I just stay at the top.
> Am I doing something wrong?

Not at all, curiously, I get the correct behavior doing exactly that.

This is strange, as this feature only stores the timestamp from slack.el
and calls slack-buffer-goto with the timestamp. I don't see what could
go wrong here.

When you call M-x org-toggle-link-display to find out what is the value
of the link, do you have the timestamp in the link part?

> Also I agree with you: we can just make the following transformation
>
> [emacs-slack:TEAM - #CHANNEL - TIME.STAMP] -> (:team TEAM :channel CHANNEL :timestamp TIME.STAMP)
>
> so that we pass a structure ("the parsed object") that represent the link information around.

I totally agree.

> By the way have you checked this function in emacs-slack
>slack-buffer.el:
>
> ```
> (defun slack-buffer-goto (ts)
>   (let ((point (slack-buffer-ts-eq (point-min) (point-max) ts)))
>     (when point
>       (goto-char point))))
> ```
> I sort of think you need that to move to the right place. 

I use it in the part about following the link (https://github.com/ag91/ol-emacs-slack/pull/2/commits/83278c3088258519bfc95d1e0a4995374fbcf0ea#diff-c7e8ab14249ae06257aa37336fd0a8969fab2df099e2526470a65ca12246a6dbR111).

> Although I guess it would not work if your message is not among the
> messages loaded so far.

Indeed, this is an issue. I think this should be improved with calls to
slack-buffer-load-mode and/or fallback on a local history mechanism if
any is provided. This can quickly become tricky, therefore I though I
would make one step at a time, and push this version and improve it
later, as I think this partially implemented feature already as value
per se.

Also, I use several teams and use slack-prefer-current-team, and the
link works only if I have selected the team that has the channel
referred to in the link. This is also an issue, but I think it can be
handled later.

Do you think we should extend this pull request to tackle the whole
feature or could we stick with the "only if the message is already
loaded" first?

My best,
-- 
Konubinix
GPG Key    : 7439106A
Fingerprint: 5993 BE7A DA65 E2D9 06CE  5C36 75D2 3CED 7439 106A

2020-11-11 15:59 UTC, ag91 commented
Yes, let's keep this small and open issues about those other points. I am going to test more carefully this to make sure it works for the scope we agreed.

2020-11-18 13:34 UTC, Konubinix commented
For what it's worth, I have been using the feature successfully a few time the past few days :-). I realized though that if the buffer is not loaded yet, the slack-goto-ts does nothing and another org-link-open is needed to move to the correct timestamp.

Is it possible your issue was raised in the same situation?

2020-11-18 13:40 UTC, ag91 requested changes

2020-11-18 13:42 UTC, ag91 commented
lol, sorry I reviewed this a few days ago but I did not realize I need to press submit review. If you can add that code I will merge it in.
I guess you do not have channels looking `some-channel` in your account?

2020-11-19 08:12 UTC, Konubinix commented
Nope. I will provide another pull request to correctly parse/format the link and adapt this PR on top of the other one.

Fun fact, yesterday, I wanted to add org links in ledger mode and almost did the (s-split ...) parsing everywhere before thinking I need to learn from my experience and added dedicated functions to parse and format the link :-P.

2020-11-19 12:58 UTC, Konubinix commented
I am giving a look at formatting and parsing messages and saw `slack-message-notification-title-format-function` is used to format the link. The code tries to find out whether the message was in a thread so that `slack-message-notification-title-format-function` can put "Thread in #" in the message. This information is not used by the follow link part and is neither shown in the link description.

I would like to start simple and replace this by a more traditional (and easily parsable) "team_name|room_name|ts:timestamp".

I used positional semantic for team and room because they will always be there and key:value semantic for the timestamp because it is optional. I tried to use as a separator a character that I would not expect in a team name or a room name : '|'.

What do you think about this?

2020-11-19 12:59 UTC, Konubinix commented
To be noted that this would break previous links, but would be generic enough to undergo future modifications while keeping retro-compatibility.

2020-11-19 13:46 UTC, ag91 commented
Mmm, I would keep things backwards compatible all the time. Also I seem to remember that function will also display the message differently in the modeline, no?
Maybe we can just merge this as is, and create a new MR for the link structure and how to parse it? We can even pair program on it if you have ~1hr of free time.

2020-11-19 14:00 UTC, ag91 commented
Mmm, I would keep things backwards compatible all the time. Also I seem to remember that function will also display the message differently in the modeline, no?

Maybe we can just merge this as is, and create a new MR for the link structure and how to parse it? We can even pair program on it if you have ~1hr of free time.

2020-11-19 14:08 UTC, Konubinix commented
Peer programming would be great. I live in France, so UTC+1. We can discuss the logistic further by email I you prefer :-).

About the backward compatible part, I think the current code is far from ideal, but we could add a "sanity check" to parse the old format if need be.

2020-11-19 14:13 UTC, Konubinix commented
I just pushed another version, removing most of the parsing code to let slack.el do the job. It works pretty well so far.

Can you try it and tell me what you think?

I did not add the backward compatibility code, and I wonder if we could let it go, the code to handle the backward compatibility would take more than half of the total code :-/.

2020-11-19 14:14 UTC, Konubinix commented
Finally, I did not starts a new pull request, because it looks more like a rewrite than a simple feature.

2020-11-19 14:16 UTC, Konubinix commented
Strangely (and fortunately), slack-room-find already does the work of finding out whether it is an IM, a group, a channel etc

2020-11-19 14:18 UTC, Konubinix commented
Also, because I use IDs, we could go back to using more standard separators, like '-' if you like. I must admit I prefer the implementation with the link containing ids much more than the one containing a name and some code to try to find the correct room.

Also, with this implementation, the code won't break in case you are not in the slack prefered team, because it first resolves the team and finds the room in the team.

2020-11-20 18:23 UTC, ag91 commented
It works for me and I like that you cut out a lot of complex code. Good
work finding out that emacs-slack function! And nice thinking about ids!

I still would prefer compatibility: what about you move the earlier code
in a ol-slack-legacy.el?

Then you can just require that and have a little function that tries to convert
an old link in a new one, if invalid. For example for getting the team identifier is as easy as
`(oref (ol/slack-string-to-team "someTeamName") id)`.

I just do not know how others are using these links and breaking them
does not sound nice (also I have got quite some of them myself XD).

Actually I could also just write a little migration elisp script that
converts all old links in the new format?


On Thu 19 Nov 2020 at 15:18, Samuel Loury <notifications@github.com> wrote:

> Also, because I use IDs, we could go back to using more standard separators, like '-' if you like. I must admit I prefer the implementation with the link containing ids much more than the one containing a name and some code to try to find the correct room.
>
> Also, with this implementation, the code won't break in case you are not in the slack prefered team, because it first resolves the team and finds the room in the team.

2020-11-23 13:38 UTC, Konubinix commented
Hi,

ag91 <notifications@github.com> writes:

[...]

> Then you can just require that and have a little function that tries to convert
> an old link in a new one, if invalid. For example for getting the team identifier is as easy as
> `(oref (ol/slack-string-to-team "someTeamName") id)`.

I can try and propose something indeed :-).

-- 
Konubinix
GPG Key    : 7439106A
Fingerprint: 5993 BE7A DA65 E2D9 06CE  5C36 75D2 3CED 7439 106A

2020-12-08 13:23 UTC, Konubinix commented
Hi,

I detected links without the | character and run the legacy code on them, so that legacy links work as well.

Also, I made the code warn the user that this is a legacy link and it should be updated, with the possibility to silence the warning.

What do you think of this?

2020-12-08 13:25 UTC, Konubinix commented
I kind of like the new style links. I use them a lot as they have become part of my everyday usage. It is very convenient to be able to capture a TODO based on a specific message of a collegue or store the link to some discussion in my personal notes.

Thanks for the ol/slack package :-).

2020-12-08 13:26 UTC, Konubinix commented
Also, I realize I have not yet been confronted to the limitation of ol/slack failing to find the message because it is not loaded. But for sure, when this happen I will write the code to overcome this limitation ;-).

2020-12-09 10:10 UTC, ag91 commented
@Konubinix thank you! This is a fantastic contribution!! And it is amazing I can still use my old entries: well done :+1: 
I really appreciate your work on this, impressed. I shall ping you, so we can pair at some point, I am really curious.

2020-12-09 10:10 UTC, merged

2020-12-09 11:04 UTC, Konubinix commented
I'm glad it helped